name: SonarQube Analysis

on:
  push:
    branches:
      - main  # or the branch you want to analyze
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarQube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Cache SonarQube packages
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-${{ hashFiles('**/*.gradle*', '**/*.java*', '**/*.kt') }}
          restore-keys: |
            ${{ runner.os }}-sonar-

      - name: Install SonarQube Scanner
        run: |
          curl -sSLo /tmp/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
          unzip /tmp/sonar-scanner.zip -d ~/.sonar
          mv ~/.sonar/sonar-scanner-4.6.2.2472-linux ~/.sonar/sonar-scanner

      - name: Add SonarQube Scanner to PATH
        run: echo "${HOME}/.sonar/sonar-scanner/bin" >> $GITHUB_PATH

      - name: Run SonarQube Scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
          -Dsonar.projectKey=<your_project_key> \
          -Dsonar.host.url=http://<your_sonarqube_server_url>:9000 \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
